### ISSUE TITLE
Error: Invalid parameter: only messages with role 'assistant' can have a function call.

### ISSUE THREAD

**Issue by jordanhindo** [amadad/agentcy#4]
When the writing assistant tries to call the research function, there is an error:
"openai.error.InvalidRequestError: Invalid parameter: only messages with role 'assistant' can have a function call."

This happens with both gpt-4 and 3.5-turbo. 

```I codified the most important parts like this box```

Agency_Copywriter (to chat_manager):

Great work, Agency Strategist! The strategic brief provides a clear roadmap for the development of the Experimental Bass Music Database. It effectively outlines the brand's positioning, target audience, and unique value proposition. The key messages and emotional appeal are well-defined, and the strategic initiatives align with the goal of building a comprehensive and trusted resource.

Next, let's collaborate with the Agency Designer to ensure that the visual elements and user experience complement the brand's voice and strategic direction. By aligning the text and visuals, we can create a cohesive brand story that resonates with the target audience. Let's continue working together to bring the Experimental Bass Music Database to life!

--------------------------------------------------------------------------------
[autogen.oai.completion: 11-01 17:10:44] {223} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\oai\completion.py", line 209, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 3a48ccdd1f5a96586718e2f31f005694 in your email.) {
  "error": {
    "message": "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 3a48ccdd1f5a96586718e2f31f005694 in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 3a48ccdd1f5a96586718e2f31f005694 in your email.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 02 Nov 2023 00:10:14 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-model': 'gpt-3.5-turbo-0613', 'openai-organization': 'zenchant', 'openai-processing-ms': '852', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '5000', 'x-ratelimit-limit-tokens': '90000', 'x-ratelimit-remaining-requests': '4999', 'x-ratelimit-remaining-tokens': '84399', 'x-ratelimit-reset-requests': '12ms', 'x-ratelimit-reset-tokens': '3.733s', 'x-request-id': '3a48ccdd1f5a96586718e2f31f005694', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '81f82738a9ab6a04-SMF', 'alt-svc': 'h3=":443"; ma=86400'}
[autogen.oai.completion: 11-01 17:11:03] {223} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\oai\completion.py", line 209, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 09955dfb9dc7289f412373a1dc8d3255 in your email.) {
  "error": {
    "message": "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 09955dfb9dc7289f412373a1dc8d3255 in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 09955dfb9dc7289f412373a1dc8d3255 in your email.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 02 Nov 2023 00:10:33 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-model': 'gpt-3.5-turbo-0613', 'openai-organization': 'zenchant', 'openai-processing-ms': '8412', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '5000', 'x-ratelimit-limit-tokens': '90000', 'x-ratelimit-remaining-requests': '4999', 'x-ratelimit-remaining-tokens': '87783', 'x-ratelimit-reset-requests': '12ms', 'x-ratelimit-reset-tokens': '1.477s', 'x-request-id': '09955dfb9dc7289f412373a1dc8d3255', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '81f8277ebdb26a04-SMF', 'alt-svc': 'h3=":443"; ma=86400'}
writing_assistant (to chat_manager):

```
******* Suggested function Call: research *****
Arguments:
{
  "query": "Experimental Bass Music"
}
***********************************************
```

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Zenchant\Documents\agentcy\main.py", line 448, in <module>
    user_proxy.initiate_chat(
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 521, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 324, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 452, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 764, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\groupchat.py", line 116, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\groupchat.py", line 45, in select_speaker
    final, name = selector.generate_oai_reply(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 596, in generate_oai_reply
    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\oai\completion.py", line 773, in create
    response = cls.create(
               ^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\oai\completion.py", line 804, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\autogen\oai\completion.py", line 209, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Zenchant\Documents\agentcy\myenv\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
`openai.error.InvalidRequestError: Invalid parameter: only messages with role 'assistant' can have a function call.`

**Comment by amadad** [comment]
Hi there. Please try resending your request, as transient server issues, which are often quickly resolved, may have caused the error. The role type for the research function call is addressed in the latest code—which I will push today.

**Comment by mrmaiko** [comment]
The appears to still be happening.

**Comment by amadad** [comment]
I pushed a new version, can you try that.

**Comment by mrmaiko** [comment]
It sem

> I pushed a new version, can you try that.

It seems to work now. I'm just not sure about when/where/and if I am to provide input via the command line. It seems to pause after it's different phases for long periods of time. Should we be submitting information via the command prompt to interact with this?

**Comment by amadad** [comment]
There is an initial input, two questions, and depending on the phase or stage feedback is requested (or can be skipped). That should be clearly indicated as a prompt or question in the CLI—this is an AutoGen feature for the User Proxy. Can you post any screenshots with notes around issues and expectations, ie. what you thought it might do vs what it did? Thanks.
